#!/usr/bin/env python3
# Permanent GMFE69 post-generation optimizations.
#
# Generated DolRecomp C files and multi_module_export.c are disposable. This
# module reapplies the validated Medal of Honor: Frontline optimizations every
# time they are generated by tools/build_all_exec_module.py.

from __future__ import annotations

import re
from pathlib import Path

HOT_FP_CHUNKS = ("8007AE80", "800F2E80", "800F6E80", "8013EE80", "80142E80")

FP_MARK = "MOH_FAST_FP_AVAILABILITY"
FP_HELPER = r'''
/* MOH_FAST_FP_AVAILABILITY
 * MSR[FP] is overwhelmingly enabled in these GMFE69 hot chunks.
 * Preserve the exact slow helper when it is actually clear.
 */
static inline bool mg_fp_available_fast(CPUState* cpu, u32 cia)
{
#if defined(__GNUC__) || defined(__clang__)
    if (__builtin_expect((cpu->msr & PPC_MSR_FP) != 0, 1))
#else
    if ((cpu->msr & PPC_MSR_FP) != 0)
#endif
        return true;
    return ppc_fp_available(cpu, cia);
}
#define ppc_fp_available(cpu_, cia_) mg_fp_available_fast((cpu_), (cia_))
'''

PARTICLE_LFD_TARGETS = {
    0x8007E198: (0, 4, 864),
    0x8007E1B8: (0, 0, 856),
    0x8007E1E0: (0, 0, 848),
    0x8007E200: (2, 0, 840),
    0x8007E260: (0, 0, 832),
    0x8007E2B0: (0, 4, 816),
    0x8007E2BC: (0, 0, 808),
    0x8007E2D4: (3, 5, 824),
    0x8007E408: (2, 0, 784),
    0x8007E410: (3, 6, 800),
    0x8007E430: (1, 4, 792),
}
PARTICLE_STACK_TARGETS = {
    0x8007E190: 868,
    0x8007E1B0: 860,
    0x8007E1D4: 852,
    0x8007E1F4: 844,
    0x8007E258: 836,
    0x8007E29C: 820,
    0x8007E2B4: 812,
}
PARTICLE_RNG_TARGETS = {
    0x8007E188: 4,
    0x8007E1A0: 0,
    0x8007E1C0: 4,
    0x8007E1E8: 4,
    0x8007E22C: 0,
    0x8007E290: 6,
    0x8007E2F0: 4,
    0x8007E31C: 3,
    0x8007E368: 4,
    0x8007E418: 5,
    0x8007E450: 3,
}

LFD_MARK = "MOH_PARTICLE_LFD_FASTPATH"
STACK_HELPER_MARK = "MOH_PARTICLE_STACK_WRITE_HELPER"
STACK_MARK = "MOH_PARTICLE_STACK_WRITE_FASTPATH"
RNG_MARK = "MOH_PARTICLE_RNG_WRITE_FASTPATH"
MEM1_MARK = "MOH_PARTICLE_MEM1_SINGLE_CHECK"
RESERVE_MARK = "MOH_PARTICLE_RESERVE_UNLIKELY"

PARTICLE_HELPER = r'''
/* MOH_PARTICLE_STACK_WRITE_HELPER
 *
 * Exact fast path for CParticleSystem::RenderSystem hot MEM1 writes.
 * It preserves mem_write32's reservation invalidation, SMC/write journal,
 * big-endian store and generic fallback semantics.
 */
#if defined(__GNUC__) || defined(__clang__)
#define MOH_PARTICLE_ALWAYS_INLINE __attribute__((always_inline))
#else
#define MOH_PARTICLE_ALWAYS_INLINE
#endif
static inline MOH_PARTICLE_ALWAYS_INLINE
void moh_particle_stack_write32(CPUState* cpu, u32 addr, u32 value)
{
    const u32 offset = addr - GC_RAM_BASE;

    /* MOH_PARTICLE_MEM1_SINGLE_CHECK:
     * ram_size is always >= 4 for a valid GameCube CPUState. */
#if defined(__GNUC__) || defined(__clang__)
    if (__builtin_expect(offset <= (cpu->ram_size - 4u), 1))
#else
    if (offset <= (cpu->ram_size - 4u))
#endif
    {
#if defined(__GNUC__) || defined(__clang__)
        if (__builtin_expect(cpu->reserve_valid != 0, 0))
#else
        if (cpu->reserve_valid)
#endif
        {
            /* MOH_PARTICLE_RESERVE_UNLIKELY:
             * lwarx/stwcx reservation is normally inactive in particle traffic.
             * Exact invalidation semantics are retained when it is active. */
            const u32 reserve_addr = cpu->reserve_addr & ~0x40000000u;
            const u32 store_addr = addr & ~0x40000000u;
            if (((reserve_addr ^ store_addr) & ~31u) == 0u)
                cpu->reserve_valid = false;
        }

        if (g_mem_write_journal)
            g_mem_write_journal(offset, 4u, g_mem_write_journal_user);

        write_be32(cpu->ram + offset, value);
        return;
    }

    mem_write32(cpu, addr, value);
}
#undef MOH_PARTICLE_ALWAYS_INLINE
'''


def _block_bounds(text: str, pc: int) -> tuple[int, int]:
    label = f"label_{pc:08X}:"
    start = text.find(label)
    if start < 0:
        raise RuntimeError(f"missing {label}")
    tail = text[start + len(label):]
    match = re.search(r"\nlabel_[0-9A-Fa-f]{8}:", tail)
    end = len(text) if not match else start + len(label) + match.start()
    return start, end


def _find_chunk(chunks: Path, address: str) -> Path | None:
    matches = sorted(chunks.glob(f"*_{address}.c"))
    if not matches:
        matches = sorted(chunks.glob(f"*_{address.lower()}.c"))
    if len(matches) > 1:
        raise RuntimeError(f"{address}: expected at most one generated chunk, found {len(matches)}")
    return matches[0] if matches else None


def _patch_hot_fp(path: Path) -> bool:
    text = path.read_text()
    if FP_MARK in text or "MOH fast FP availability hot-chunk path" in text:
        return False
    needle = '#include "../generated.h"\n'
    if needle not in text:
        raise RuntimeError(f"{path}: generated include anchor not found")
    path.write_text(text.replace(needle, needle + FP_HELPER + "\n", 1))
    return True


def _inject_particle_helper(text: str) -> str:
    if STACK_HELPER_MARK in text:
        return text
    fn = re.search(
        r"(?m)^[A-Za-z_][A-Za-z0-9_ \t\*]*\bmg_img\d+_func_8007AE80\s*\(",
        text,
    )
    if not fn:
        raise RuntimeError("particle helper: generated 0x8007AE80 function declaration not found")
    return text[:fn.start()] + PARTICLE_HELPER + "\n" + text[fn.start():]


def _patch_particle_lfd(text: str) -> str:
    for pc in sorted(PARTICLE_LFD_TARGETS, reverse=True):
        dest, src, off = PARTICLE_LFD_TARGETS[pc]
        start, end = _block_bounds(text, pc)
        block = text[start:end]
        if LFD_MARK in block:
            continue
        pattern = re.compile(
            r"\{\s*u32 ea = ctx->gpr\[1\] \+ \(u32\)\(s32\)\(" + str(off) + r"\);\s*"
            + rf"ctx->fpr\[{dest}\] = dolrecomp_f64_from_bits\(mem_read64\(ctx, ea\)\);\s*\}}",
            re.S,
        )
        match = pattern.search(block)
        if not match:
            raise RuntimeError(f"{pc:08X}: expected particle lfd mem_read64 block not found")
        replacement = (
            "{\n"
            f"        /* {LFD_MARK}: bit-exact guest-stack lfd reconstruction. */\n"
            f"        const u32 moh_rng_low = (ctx->gpr[{src}] & 0x00007FFFu) ^ 0x80000000u;\n"
            "        const u64 moh_rng_bits = ((u64)ctx->gpr[29] << 32) | (u64)moh_rng_low;\n"
            f"        ctx->fpr[{dest}] = dolrecomp_f64_from_bits(moh_rng_bits);\n"
            "    }"
        )
        block = block[:match.start()] + replacement + block[match.end():]
        text = text[:start] + block + text[end:]
    return text


def _patch_particle_stack(text: str) -> str:
    text = _inject_particle_helper(text)
    for pc in sorted(PARTICLE_STACK_TARGETS, reverse=True):
        off = PARTICLE_STACK_TARGETS[pc]
        start, end = _block_bounds(text, pc)
        block = text[start:end]
        if STACK_MARK in block:
            continue
        comment = re.search(rf"//\s*{pc:08X}:\s*stw\s+r(\d+),\s*{off}\(r1\)", block)
        if not comment:
            raise RuntimeError(f"{pc:08X}: expected `stw r?, {off}(r1)` not found")
        src = int(comment.group(1))
        pattern = re.compile(
            r"\{\s*u32\s+ea\s*=\s*ctx->gpr\[1\]\s*\+\s*"
            r"\(u32\)\(s32\)\(" + re.escape(str(off)) + r"\)\s*;\s*"
            rf"mem_write32\(ctx,\s*ea,\s*\(u32\)ctx->gpr\[{src}\]\);\s*\}}",
            re.S,
        )
        match = pattern.search(block)
        if not match:
            raise RuntimeError(f"{pc:08X}: expected particle stack mem_write32 block not found")
        replacement = (
            "{\n"
            f"        /* {STACK_MARK}: cached-MEM1 stack write, generic fallback retained. */\n"
            f"        u32 ea = ctx->gpr[1] + (u32)(s32)({off});\n"
            f"        moh_particle_stack_write32(ctx, ea, (u32)ctx->gpr[{src}]);\n"
            "    }"
        )
        block = block[:match.start()] + replacement + block[match.end():]
        text = text[:start] + block + text[end:]
    return text


def _patch_particle_rng(text: str) -> str:
    for pc in sorted(PARTICLE_RNG_TARGETS, reverse=True):
        src = PARTICLE_RNG_TARGETS[pc]
        start, end = _block_bounds(text, pc)
        block = text[start:end]
        if RNG_MARK in block:
            continue
        if not re.search(rf"//\s*{pc:08X}:\s*stw\s+r{src},\s*-28436\(r13\)", block):
            raise RuntimeError(f"{pc:08X}: expected RNG stw r{src}, -28436(r13) not found")
        pattern = re.compile(
            r"\{\s*u32\s+ea\s*=\s*ctx->gpr\[13\]\s*\+\s*"
            r"\(u32\)\(s32\)\(-28436\)\s*;\s*"
            rf"mem_write32\(ctx,\s*ea,\s*\(u32\)ctx->gpr\[{src}\]\);\s*\}}",
            re.S,
        )
        match = pattern.search(block)
        if not match:
            raise RuntimeError(f"{pc:08X}: expected RNG mem_write32 block not found")
        replacement = (
            "{\n"
            f"        /* {RNG_MARK}: hot RNG seed write via cached-MEM1 fast path. */\n"
            "        u32 ea = ctx->gpr[13] + (u32)(s32)(-28436);\n"
            f"        moh_particle_stack_write32(ctx, ea, (u32)ctx->gpr[{src}]);\n"
            "    }"
        )
        block = block[:match.start()] + replacement + block[match.end():]
        text = text[:start] + block + text[end:]
    return text


def apply_gmfe69_generated_postgen(generated: Path) -> None:
    generated = Path(generated)
    chunks = generated / "chunks"
    if not chunks.is_dir():
        raise RuntimeError(f"GMFE69 postgen: missing chunks directory: {chunks}")

    for address in HOT_FP_CHUNKS:
        path = _find_chunk(chunks, address)
        if path:
            _patch_hot_fp(path)

    particle = _find_chunk(chunks, "8007AE80")
    if not particle:
        return

    text = particle.read_text()
    if "MOH_PARTICLE_DEAD_STACK_STORE" in text:
        raise RuntimeError(
            "GMFE69 postgen: obsolete dead-stack-store experiment is present; "
            "regenerate this chunk from clean DolRecomp output first"
        )
    text = _patch_particle_lfd(text)
    text = _patch_particle_stack(text)
    text = _patch_particle_rng(text)
    particle.write_text(text)

    checks = {
        LFD_MARK: 11,
        STACK_MARK: 7,
        RNG_MARK: 11,
        STACK_HELPER_MARK: 1,
        MEM1_MARK: 1,
        RESERVE_MARK: 1,
    }
    final = particle.read_text()
    for marker, expected in checks.items():
        count = final.count(marker)
        if count != expected:
            raise RuntimeError(
                f"GMFE69 postgen: {particle.name}: marker {marker} count={count}, expected={expected}"
            )


def _image_dispatch_cases(text: str) -> list[tuple[int, str]]:
    cases = [
        (int(index), name)
        for index, name in re.findall(
            r"case\s+(\d+)u:\s+return\s+(mg_image_\d+_dispatch)\(ctx,\s*address\);",
            text,
        )
    ]
    if not cases:
        raise RuntimeError("GMFE69 export postgen: image dispatch cases not found")
    return cases


def _final_burst(cases: list[tuple[int, str]]) -> str:
    case_lines = "".join(
        f"            case {index}u: dispatched = {name}(ctx, pc); break;\n"
        for index, name in cases
    )
    return (
        "static u32 chassis_dispatch_burst(\n"
        "    CPUState* ctx,\n"
        "    u32 address,\n"
        "    const u8* chain_state,\n"
        "    u32 chain_state_count,\n"
        "    u64 cycle_budget,\n"
        "    u64 timebase_origin,\n"
        "    u64 timebase_cycles_before,\n"
        "    u32 timebase_ratio)\n"
        "{\n"
        "    /* MOH_GMFE69_BURST_POSTGEN: validated multi-image native burst. */\n"
        "    multi_init_once();\n"
        "    if (!chain_state || chain_state_count == 0u || cycle_budget == 0u) return 0u;\n"
        "    u32 blocks = 0u;\n"
        "    u64 total_cycles = 0u;\n"
        "    int cached_chunk = -1;\n"
        "    u32 cached_chunk_start = 0u;\n"
        "    u32 cached_chunk_end = 0u;\n"
        "    ctx->pc = address;\n"
        "    while (blocks < 64u && total_cycles < cycle_budget) {\n"
        "        const u32 pc = ctx->pc;\n"
        "        int chunk = cached_chunk;\n"
        "        if (chunk < 0 || pc < cached_chunk_start || pc >= cached_chunk_end) {\n"
        "            chunk = multi_chunk_index(pc);\n"
        "            if (chunk < 0) break;\n"
        "            cached_chunk = chunk;\n"
        "            cached_chunk_start = s_chunk_ranges[(u32)chunk].start;\n"
        "            cached_chunk_end = s_chunk_ranges[(u32)chunk].end;\n"
        "        }\n"
        "        if ((u32)chunk >= chain_state_count || chain_state[(u32)chunk] == 0u) break;\n"
        "        const u32 begin = s_variant_offsets[(u32)chunk];\n"
        "        const u32 end = s_variant_offsets[(u32)chunk + 1u];\n"
        "        /* Never burst through an address range shared by executable images. */\n"
        "        if (end - begin != 1u) break;\n"
        "        const u32 image = s_active_image[(u32)chunk];\n"
        "        if (image == MULTI_INVALID_IMAGE) break;\n"
        "        ctx->downcount = 0;\n"
        "        int dispatched = 0;\n"
        "        switch (image) {\n"
        + case_lines +
        "            default: break;\n"
        "        }\n"
        "        if (!dispatched) break;\n"
        "        const s64 raw_charge = -ctx->downcount;\n"
        "        const u64 charge = raw_charge > 0 ? (u64)raw_charge : 1u;\n"
        "        total_cycles += charge;\n"
        "        ++blocks;\n"
        "        if (timebase_ratio != 0u) {\n"
        "            const u64 tb_cycles = timebase_cycles_before + total_cycles;\n"
        "            u64 tb_delta;\n"
        "#if defined(__GNUC__) || defined(__clang__)\n"
        "            if (__builtin_expect(timebase_ratio == 12u, 1))\n"
        "#else\n"
        "            if (timebase_ratio == 12u)\n"
        "#endif\n"
        "                tb_delta = tb_cycles / 12u;\n"
        "            else\n"
        "                tb_delta = chassis_div_u64_u32(tb_cycles, timebase_ratio);\n"
        "            ctx->timebase = timebase_origin + tb_delta;\n"
        "        }\n"
        "        ctx->downcount = 0;\n"
        "        if (ctx->exception) break;\n"
        "    }\n"
        "    ctx->downcount = -(s64)total_cycles;\n"
        "    return blocks;\n"
        "}\n\n"
    )


DIV_HELPER = r'''#if defined(__GNUC__) || defined(__clang__)
__attribute__((noinline))
#endif
static u64 chassis_div_u64_u32(u64 value, u32 divisor)
{
    return value / divisor;
}

'''


def apply_gmfe69_export_postgen(path: Path) -> None:
    path = Path(path)
    text = path.read_text()
    cases = _image_dispatch_cases(text)
    state_anchor = "static void chassis_on_state_loaded(CPUState* ctx)\n"
    if state_anchor not in text:
        raise RuntimeError("GMFE69 export postgen: chassis_on_state_loaded anchor not found")

    start = text.find("static u32 chassis_dispatch_burst(")
    if start < 0:
        start = text.find("static int chassis_dispatch_burst(")
    if start >= 0:
        end = text.find(state_anchor, start)
        if end < 0:
            raise RuntimeError("GMFE69 export postgen: malformed existing burst function")
        # Remove a previously-emitted divider helper immediately before the burst
        # only if it is in this generated export; it is reinserted canonically below.
        helper_start = text.rfind("#if defined(__GNUC__) || defined(__clang__)", 0, start)
        if helper_start >= 0 and "static u64 chassis_div_u64_u32" in text[helper_start:start]:
            start = helper_start
        text = text[:start] + _final_burst(cases) + text[end:]
    else:
        pos = text.find(state_anchor)
        text = text[:pos] + _final_burst(cases) + text[pos:]

    burst_pos = text.find("static u32 chassis_dispatch_burst(")
    if "static u64 chassis_div_u64_u32(" not in text:
        text = text[:burst_pos] + DIV_HELPER + text[burst_pos:]

    descriptor_pattern = re.compile(
        r"(?m)^(\s*)(?:0|chassis_dispatch_burst)\s*,[^\n]*\n"
        r"(\s*multi_select_chunk_variant\s*,)"
    )
    matches = list(descriptor_pattern.finditer(text))
    if not matches:
        raise RuntimeError("GMFE69 export postgen: burst descriptor field not found")
    match = matches[-1]
    indent = match.group(1)
    text = (
        text[:match.start()]
        + f"{indent}chassis_dispatch_burst, /* unique-image chunks only */\n"
        + match.group(2)
        + text[match.end():]
    )
    path.write_text(text)

    final = path.read_text()
    required = (
        "MOH_GMFE69_BURST_POSTGEN",
        "cached_chunk_start",
        "int dispatched = 0;",
        "chassis_div_u64_u32",
        "timebase_ratio == 12u",
        "chassis_dispatch_burst, /* unique-image chunks only */",
    )
    for marker in required:
        if marker not in final:
            raise RuntimeError(f"GMFE69 export postgen: missing verification marker: {marker}")
    burst_start = final.find("static u32 chassis_dispatch_burst(")
    burst_end = final.find(state_anchor, burst_start)
    burst = final[burst_start:burst_end]
    if "chassis_dispatch(ctx, pc)" in burst:
        raise RuntimeError("GMFE69 export postgen: second binary-search dispatcher survived in burst")


__all__ = (
    "apply_gmfe69_generated_postgen",
    "apply_gmfe69_export_postgen",
)
