#!/usr/bin/env python3
# Permanent GMFE69 post-generation optimizations.
#
# Generated DolRecomp C files and multi_module_export.c are disposable. This
# module reapplies the validated Medal of Honor: Frontline optimizations every
# time they are generated by tools/build_all_exec_module.py.

from __future__ import annotations

import re
from pathlib import Path

# MOH_GMFE69_FINAL_DEFINITIVE_OPTIMIZATIONS

HOT_FP_CHUNKS = ("8007AE80", "800F2E80", "800F6E80", "8013EE80", "80142E80")

FP_MARK = "MOH_FAST_FP_AVAILABILITY"
FP_HELPER = r'''
/* MOH_FAST_FP_AVAILABILITY
 * MSR[FP] is overwhelmingly enabled in these GMFE69 hot chunks.
 * Preserve the exact slow helper when it is actually clear.
 */
static inline bool mg_fp_available_fast(CPUState* cpu, u32 cia)
{
#if defined(__GNUC__) || defined(__clang__)
    if (__builtin_expect((cpu->msr & PPC_MSR_FP) != 0, 1))
#else
    if ((cpu->msr & PPC_MSR_FP) != 0)
#endif
        return true;
    return ppc_fp_available(cpu, cia);
}
#define ppc_fp_available(cpu_, cia_) mg_fp_available_fast((cpu_), (cia_))
'''

PARTICLE_LFD_TARGETS = {
    0x8007E198: (0, 4, 864),
    0x8007E1B8: (0, 0, 856),
    0x8007E1E0: (0, 0, 848),
    0x8007E200: (2, 0, 840),
    0x8007E260: (0, 0, 832),
    0x8007E2B0: (0, 4, 816),
    0x8007E2BC: (0, 0, 808),
    0x8007E2D4: (3, 5, 824),
    0x8007E408: (2, 0, 784),
    0x8007E410: (3, 6, 800),
    0x8007E430: (1, 4, 792),
}
PARTICLE_STACK_TARGETS = {
    0x8007E190: 868,
    0x8007E1B0: 860,
    0x8007E1D4: 852,
    0x8007E1F4: 844,
    0x8007E258: 836,
    0x8007E29C: 820,
    0x8007E2B4: 812,
}
PARTICLE_RNG_TARGETS = {
    0x8007E188: 4,
    0x8007E1A0: 0,
    0x8007E1C0: 4,
    0x8007E1E8: 4,
    0x8007E22C: 0,
    0x8007E290: 6,
    0x8007E2F0: 4,
    0x8007E31C: 3,
    0x8007E368: 4,
    0x8007E418: 5,
    0x8007E450: 3,
}


# MOH_PARTICLE_FMADDS_PERMANENT_POSTGEN
PARTICLE_FMADDS_TARGETS = (
    0x8007E204, 0x8007E210, 0x8007E230, 0x8007E238,
    0x8007E294, 0x8007E2E8, 0x8007E2F4,
    0x8007E30C, 0x8007E320, 0x8007E328, 0x8007E32C, 0x8007E330,
    0x8007E354, 0x8007E36C, 0x8007E37C, 0x8007E394, 0x8007E3A0,
    0x8007E3F0, 0x8007E404, 0x8007E40C, 0x8007E424, 0x8007E444,
    0x8007E454, 0x8007E464,
    0x8007E538, 0x8007E550, 0x8007E568, 0x8007E588,
    0x8007E5A0, 0x8007E5A4, 0x8007E5A8, 0x8007E5B0, 0x8007E5B4,
    0x8007E5B8, 0x8007E5CC, 0x8007E5D4, 0x8007E5E0, 0x8007E5E4,
    0x8007E5EC,
)

# MOH_PARTICLE_STACK_LFS_PERMANENT_POSTGEN

# MOH_PARTICLE_PSQ_PAIR_PERMANENT_POSTGEN
PSQ_PAIR_SITE_MARK = "MOH_GMFE69_PSQ_PAIR_SITE"
PSQ_PAIR_PROTO_MARK = "MOH_GMFE69_PSQ_PAIR_PROTO"

PSQ_PAIR_PROTO = r"""
/* MOH_GMFE69_PSQ_PAIR_PROTO */
extern bool ppc_psq_load0_pair_gmfe69_fast(
    CPUState* cpu, u8 frD, u32 ea, u32 cia);
extern bool ppc_psq_store0_pair_gmfe69_fast(
    CPUState* cpu, u8 frS, u32 ea, u32 cia);

"""

PSQ_PAIR_LOAD_RE = re.compile(
    r'ppc_psq_load\(\s*ctx\s*,\s*(\d+)u\s*,\s*ea\s*,\s*'
    r'false\s*,\s*0u\s*,\s*false\s*,\s*(0x[0-9A-Fa-f]+u)\s*\)'
)

PSQ_PAIR_STORE_RE = re.compile(
    r'ppc_psq_store\(\s*ctx\s*,\s*(\d+)u\s*,\s*ea\s*,\s*'
    r'false\s*,\s*0u\s*,\s*false\s*,\s*(0x[0-9A-Fa-f]+u)\s*\)'
)

STACK_LFS_MARK = "MOH_PARTICLE_STACK_LFS_FASTPATH"
STACK_LFS_HELPER_MARK = "MOH_PARTICLE_STACK_LFS_HELPER"

STACK_LFS_HELPER = r"""
/* MOH_PARTICLE_STACK_LFS_HELPER
 *
 * Fast-path GameCube stack loads from MEM1. r1-backed stack addresses are
 * overwhelmingly normal MEM1; preserve exact generic memory behavior outside
 * that range.
 */
static inline __attribute__((always_inline))
u32 moh_particle_stack_read32(CPUState* cpu, u32 addr)
{
    const u32 offset = addr - GC_RAM_BASE;

#if defined(__GNUC__) || defined(__clang__)
    if (__builtin_expect(cpu->ram_size >= 4u &&
                         offset <= (cpu->ram_size - 4u), 1))
#else
    if (cpu->ram_size >= 4u &&
        offset <= (cpu->ram_size - 4u))
#endif
        return read_be32(cpu->ram + offset);

    return mem_read32(cpu, addr);
}

"""

STACK_LFS_COMMENT_RE = re.compile(
    r'//\s*([0-9A-Fa-f]{8}):\s+lfs\s+f(\d+),\s*(-?\d+)\(r1\)'
)

STACK_LFS_BODY_RE = re.compile(
    r'(?P<indent>[ \t]*)\{\s*\n'
    r'(?P=indent)[ \t]+u32 ea = ctx->gpr\[1\] \+ \(u32\)\(s32\)\((?P<off>-?\d+)\);\s*\n'
    r'(?P=indent)[ \t]+f64 value = \(f64\)dolrecomp_f32_from_bits\(mem_read32\(ctx, ea\)\);\s*\n'
    r'(?P=indent)[ \t]+ctx->fpr\[(?P<fpr>\d+)\] = value;\s*\n'
    r'(?P=indent)[ \t]+ctx->ps1\[(?P=fpr)\] = value;\s*\n'
    r'(?P=indent)\}',
    re.MULTILINE,
)

FMADDS_MARK = "MOH_PARTICLE_FMADDS_FASTPATH"
FMADDS_PROTO_MARK = "MOH_PARTICLE_FMADDS_PROTO"

LFD_MARK = "MOH_PARTICLE_LFD_FASTPATH"
STACK_HELPER_MARK = "MOH_PARTICLE_STACK_WRITE_HELPER"
STACK_MARK = "MOH_PARTICLE_STACK_WRITE_FASTPATH"
RNG_MARK = "MOH_PARTICLE_RNG_WRITE_FASTPATH"
MEM1_MARK = "MOH_PARTICLE_MEM1_SINGLE_CHECK"
RESERVE_MARK = "MOH_PARTICLE_RESERVE_UNLIKELY"

PARTICLE_HELPER = r'''
/* MOH_PARTICLE_STACK_WRITE_HELPER
 *
 * Exact fast path for CParticleSystem::RenderSystem hot MEM1 writes.
 * It preserves mem_write32's reservation invalidation, SMC/write journal,
 * big-endian store and generic fallback semantics.
 */
#if defined(__GNUC__) || defined(__clang__)
#define MOH_PARTICLE_ALWAYS_INLINE __attribute__((always_inline))
#else
#define MOH_PARTICLE_ALWAYS_INLINE
#endif
static inline MOH_PARTICLE_ALWAYS_INLINE
void moh_particle_stack_write32(CPUState* cpu, u32 addr, u32 value)
{
    const u32 offset = addr - GC_RAM_BASE;

    /* MOH_PARTICLE_MEM1_SINGLE_CHECK:
     * ram_size is always >= 4 for a valid GameCube CPUState. */
#if defined(__GNUC__) || defined(__clang__)
    if (__builtin_expect(offset <= (cpu->ram_size - 4u), 1))
#else
    if (offset <= (cpu->ram_size - 4u))
#endif
    {
        /* MOH_PARTICLE_RESERVE_UNLIKELY:
         * Compatibility marker retained for the postgen integrity check.
         * Reservation invalidation is delegated to GXRuntime; optimized builds
         * compile it out while strict/lockstep builds retain exact semantics. */
        clear_matching_reservation(cpu, addr);
        GXRUNTIME_JOURNAL_WRITE(offset, 4u);

        write_be32(cpu->ram + offset, value);
        return;
    }

    mem_write32(cpu, addr, value);
}
#undef MOH_PARTICLE_ALWAYS_INLINE
'''


def _block_bounds(text: str, pc: int) -> tuple[int, int]:
    label = f"label_{pc:08X}:"
    start = text.find(label)
    if start < 0:
        raise RuntimeError(f"missing {label}")
    tail = text[start + len(label):]
    match = re.search(r"\nlabel_[0-9A-Fa-f]{8}:", tail)
    end = len(text) if not match else start + len(label) + match.start()
    return start, end


def _find_chunk(chunks: Path, address: str) -> Path | None:
    matches = sorted(chunks.glob(f"*_{address}.c"))
    if not matches:
        matches = sorted(chunks.glob(f"*_{address.lower()}.c"))
    if len(matches) > 1:
        raise RuntimeError(f"{address}: expected at most one generated chunk, found {len(matches)}")
    return matches[0] if matches else None



# MOH_GMFE69_SPLIT_AWARE_PARTICLE_POSTGEN
def _find_chunk_for_pc(chunks: Path, pc: int) -> Path | None:
    """Find the generated C chunk that actually contains a guest PC label."""
    label = f"label_{pc:08X}:"
    matches: list[Path] = []
    for path in sorted(chunks.glob("*.c")):
        if label in path.read_text(errors="ignore"):
            matches.append(path)

    if len(matches) > 1:
        raise RuntimeError(
            f"{pc:08X}: expected exactly one generated chunk containing "
            f"{label}, found {len(matches)}"
        )
    return matches[0] if matches else None


def _patch_hot_fp(path: Path) -> bool:
    text = path.read_text()
    if FP_MARK in text or "MOH fast FP availability hot-chunk path" in text:
        return False
    needle = '#include "../generated.h"\n'
    if needle not in text:
        raise RuntimeError(f"{path}: generated include anchor not found")
    path.write_text(text.replace(needle, needle + FP_HELPER + "\n", 1))
    return True


def _inject_particle_helper(text: str) -> str:
    if STACK_HELPER_MARK in text:
        return text
    fn = re.search(
        r"(?m)^[A-Za-z_][A-Za-z0-9_ \t\*]*\bmg_img\d+_func_[0-9A-Fa-f]{8}\s*\(",
        text,
    )
    if not fn:
        raise RuntimeError("particle helper: generated 0x8007AE80 function declaration not found")
    return text[:fn.start()] + PARTICLE_HELPER + "\n" + text[fn.start():]


def _patch_particle_lfd(text: str) -> str:
    for pc in sorted(PARTICLE_LFD_TARGETS, reverse=True):
        dest, src, off = PARTICLE_LFD_TARGETS[pc]
        start, end = _block_bounds(text, pc)
        block = text[start:end]
        if LFD_MARK in block:
            continue
        pattern = re.compile(
            r"\{\s*u32 ea = ctx->gpr\[1\] \+ \(u32\)\(s32\)\(" + str(off) + r"\);\s*"
            + rf"ctx->fpr\[{dest}\] = dolrecomp_f64_from_bits\(mem_read64\(ctx, ea\)\);\s*\}}",
            re.S,
        )
        match = pattern.search(block)
        if not match:
            raise RuntimeError(f"{pc:08X}: expected particle lfd mem_read64 block not found")
        replacement = (
            "{\n"
            f"        /* {LFD_MARK}: bit-exact guest-stack lfd reconstruction. */\n"
            f"        const u32 moh_rng_low = (ctx->gpr[{src}] & 0x00007FFFu) ^ 0x80000000u;\n"
            "        const u64 moh_rng_bits = ((u64)ctx->gpr[29] << 32) | (u64)moh_rng_low;\n"
            f"        ctx->fpr[{dest}] = dolrecomp_f64_from_bits(moh_rng_bits);\n"
            "    }"
        )
        block = block[:match.start()] + replacement + block[match.end():]
        text = text[:start] + block + text[end:]
    return text


def _patch_particle_stack(text: str) -> str:
    text = _inject_particle_helper(text)
    for pc in sorted(PARTICLE_STACK_TARGETS, reverse=True):
        off = PARTICLE_STACK_TARGETS[pc]
        start, end = _block_bounds(text, pc)
        block = text[start:end]
        if STACK_MARK in block:
            continue
        comment = re.search(rf"//\s*{pc:08X}:\s*stw\s+r(\d+),\s*{off}\(r1\)", block)
        if not comment:
            raise RuntimeError(f"{pc:08X}: expected `stw r?, {off}(r1)` not found")
        src = int(comment.group(1))
        pattern = re.compile(
            r"\{\s*u32\s+ea\s*=\s*ctx->gpr\[1\]\s*\+\s*"
            r"\(u32\)\(s32\)\(" + re.escape(str(off)) + r"\)\s*;\s*"
            rf"mem_write32\(ctx,\s*ea,\s*\(u32\)ctx->gpr\[{src}\]\);\s*\}}",
            re.S,
        )
        match = pattern.search(block)
        if not match:
            raise RuntimeError(f"{pc:08X}: expected particle stack mem_write32 block not found")
        replacement = (
            "{\n"
            f"        /* {STACK_MARK}: cached-MEM1 stack write, generic fallback retained. */\n"
            f"        u32 ea = ctx->gpr[1] + (u32)(s32)({off});\n"
            f"        moh_particle_stack_write32(ctx, ea, (u32)ctx->gpr[{src}]);\n"
            "    }"
        )
        block = block[:match.start()] + replacement + block[match.end():]
        text = text[:start] + block + text[end:]
    return text


def _patch_particle_rng(text: str) -> str:
    for pc in sorted(PARTICLE_RNG_TARGETS, reverse=True):
        src = PARTICLE_RNG_TARGETS[pc]
        start, end = _block_bounds(text, pc)
        block = text[start:end]
        if RNG_MARK in block:
            continue
        if not re.search(rf"//\s*{pc:08X}:\s*stw\s+r{src},\s*-28436\(r13\)", block):
            raise RuntimeError(f"{pc:08X}: expected RNG stw r{src}, -28436(r13) not found")
        pattern = re.compile(
            r"\{\s*u32\s+ea\s*=\s*ctx->gpr\[13\]\s*\+\s*"
            r"\(u32\)\(s32\)\(-28436\)\s*;\s*"
            rf"mem_write32\(ctx,\s*ea,\s*\(u32\)ctx->gpr\[{src}\]\);\s*\}}",
            re.S,
        )
        match = pattern.search(block)
        if not match:
            raise RuntimeError(f"{pc:08X}: expected RNG mem_write32 block not found")
        replacement = (
            "{\n"
            f"        /* {RNG_MARK}: hot RNG seed write via cached-MEM1 fast path. */\n"
            "        u32 ea = ctx->gpr[13] + (u32)(s32)(-28436);\n"
            f"        moh_particle_stack_write32(ctx, ea, (u32)ctx->gpr[{src}]);\n"
            "    }"
        )
        block = block[:match.start()] + replacement + block[match.end():]
        text = text[:start] + block + text[end:]
    return text





def _patch_particle_psq_pair(text: str) -> str:
    site_count = text.count(PSQ_PAIR_SITE_MARK)
    proto_count = text.count(PSQ_PAIR_PROTO_MARK)

    # Idempotent path for an already-patched generated chunk.
    if site_count == 94:
        if proto_count != 1:
            raise RuntimeError(
                f"particle PSQ pair: already has 94 sites but "
                f"prototype count is {proto_count}, expected 1"
            )
        return text

    if site_count != 0:
        raise RuntimeError(
            f"particle PSQ pair: partial existing patch, "
            f"site marker count={site_count}"
        )

    load_matches = list(PSQ_PAIR_LOAD_RE.finditer(text))
    store_matches = list(PSQ_PAIR_STORE_RE.finditer(text))

    if len(load_matches) != 49 or len(store_matches) != 45:
        raise RuntimeError(
            "particle PSQ pair: expected 49 load + 45 store "
            "W=0/GQR0/non-indexed sites, found "
            f"{len(load_matches)} + {len(store_matches)}"
        )

    if proto_count == 0:
        include_anchor = '#include "../generated.h"\n'
        if include_anchor not in text:
            raise RuntimeError(
                "particle PSQ pair: generated include anchor not found"
            )
        text = text.replace(
            include_anchor,
            include_anchor + "\n" + PSQ_PAIR_PROTO,
            1,
        )
    elif proto_count != 1:
        raise RuntimeError(
            f"particle PSQ pair: prototype marker count={proto_count}"
        )

    def repl_load(match):
        return (
            f"ppc_psq_load0_pair_gmfe69_fast("
            f"ctx, {match.group(1)}u, ea, {match.group(2)}) "
            f"/* {PSQ_PAIR_SITE_MARK} */"
        )

    def repl_store(match):
        return (
            f"ppc_psq_store0_pair_gmfe69_fast("
            f"ctx, {match.group(1)}u, ea, {match.group(2)}) "
            f"/* {PSQ_PAIR_SITE_MARK} */"
        )

    text, nload = PSQ_PAIR_LOAD_RE.subn(repl_load, text)
    text, nstore = PSQ_PAIR_STORE_RE.subn(repl_store, text)

    if nload != 49 or nstore != 45:
        raise RuntimeError(
            f"particle PSQ pair: replacement mismatch "
            f"load={nload}, store={nstore}"
        )

    if text.count(PSQ_PAIR_SITE_MARK) != 94:
        raise RuntimeError(
            "particle PSQ pair: final site marker count != 94"
        )
    if text.count(PSQ_PAIR_PROTO_MARK) != 1:
        raise RuntimeError(
            "particle PSQ pair: final prototype marker count != 1"
        )

    return text



def _patch_particle_stack_lfs(
    text: str,
    pc_min: int = 0x8007AE80,
    pc_max: int = 0x8007EE80,
) -> tuple[str, int]:
    comments = list(STACK_LFS_COMMENT_RE.finditer(text))
    targets = [
        (int(m.group(1), 16), int(m.group(2)), int(m.group(3)))
        for m in comments
        if pc_min <= int(m.group(1), 16) < pc_max
    ]

    if not targets:
        return text, 0

    if STACK_LFS_HELPER_MARK not in text:
        include_anchor = '#include "../generated.h"\n'
        if include_anchor not in text:
            raise RuntimeError(
                "particle stack lfs: generated include anchor not found"
            )
        text = text.replace(
            include_anchor,
            include_anchor + "\n" + STACK_LFS_HELPER,
            1,
        )

    for pc, fpr, off in sorted(targets, reverse=True):
        start, end = _block_bounds(text, pc)
        block = text[start:end]

        if STACK_LFS_MARK in block:
            continue

        cm = STACK_LFS_COMMENT_RE.search(block)
        if not cm:
            raise RuntimeError(f"{pc:08X}: stack lfs comment missing")
        if int(cm.group(2)) != fpr or int(cm.group(3)) != off:
            raise RuntimeError(f"{pc:08X}: stack lfs metadata mismatch")

        bm = STACK_LFS_BODY_RE.search(block)
        if not bm:
            raise RuntimeError(
                f"{pc:08X}: standard stack lfs generated body not found"
            )
        if int(bm.group("off")) != off or int(bm.group("fpr")) != fpr:
            raise RuntimeError(f"{pc:08X}: stack lfs body mismatch")

        indent = bm.group("indent")
        replacement = (
            indent + "{\n"
            + indent + f"    u32 ea = ctx->gpr[1] + (u32)(s32)({off});\n"
            + indent + "    f64 value = (f64)dolrecomp_f32_from_bits("
              "moh_particle_stack_read32(ctx, ea)); "
              f"/* {STACK_LFS_MARK} */\n"
            + indent + f"    ctx->fpr[{fpr}] = value;\n"
            + indent + f"    ctx->ps1[{fpr}] = value;\n"
            + indent + "}"
        )

        block = block[:bm.start()] + replacement + block[bm.end():]
        text = text[:start] + block + text[end:]

    return text, len(targets)


def _patch_particle_fmadds(text: str) -> str:
    # Normalize the legacy manually-installed prototype marker first.
    # It used FMADDS_MARK itself, which made marker verification count
    # 39 call-sites + 1 prototype = 40.
    legacy_proto = (
        "/* MOH_PARTICLE_FMADDS_FASTPATH: compact exact fmadds common path. */"
    )
    if legacy_proto in text:
        text = text.replace(
            legacy_proto,
            f"/* {FMADDS_PROTO_MARK}: exact GMFE69 particle fmadds helper. */",
            1,
        )

    if FMADDS_PROTO_MARK not in text:
        fn = re.search(
            r"(?m)^[A-Za-z_][A-Za-z0-9_ \t\*]*\bmg_img\d+_func_[0-9A-Fa-f]{8}\s*\(",
            text,
        )
        if not fn:
            raise RuntimeError(
                "particle fmadds: generated 0x8007AE80 function declaration not found"
            )
        proto = (
            f"/* {FMADDS_PROTO_MARK}: exact GMFE69 particle fmadds helper. */\n"
            "extern bool ppc_fmadds_gmfe69_fast(CPUState* cpu, f64 a, f64 c, f64 b,\n"
            "                                       f64* output);\n\n"
        )
        text = text[:fn.start()] + proto + text[fn.start():]

    pattern = re.compile(
        r"ppc_fma\(\s*ctx\s*,\s*"
        r"(ctx->fpr\[\d+\])\s*,\s*"
        r"(ctx->fpr\[\d+\])\s*,\s*"
        r"(ctx->fpr\[\d+\])\s*,\s*"
        r"true\s*,\s*false\s*,\s*false\s*,\s*&result\s*\)"
    )

    for pc in sorted(PARTICLE_FMADDS_TARGETS, reverse=True):
        start, end = _block_bounds(text, pc)
        block = text[start:end]
        if FMADDS_MARK in block:
            continue

        matches = list(pattern.finditer(block))
        if len(matches) != 1:
            raise RuntimeError(
                f"{pc:08X}: expected exactly one particle fmadds ppc_fma "
                f"(true,false,false), found {len(matches)}"
            )

        match = matches[0]
        replacement = (
            f"ppc_fmadds_gmfe69_fast(ctx, {match.group(1)}, {match.group(2)}, "
            f"{match.group(3)}, &result) /* {FMADDS_MARK} */"
        )
        block = block[:match.start()] + replacement + block[match.end():]
        text = text[:start] + block + text[end:]

    return text



# MOH_GMFE69_GLOBAL_PSQ_PAIR_PERMANENT
PSQ_PAIR_GLOBAL_MARK = "MOH_GMFE69_PSQ_PAIR_GLOBAL_SITE"


def _patch_global_psq_pair_generated(generated: Path) -> tuple[int, int]:
    """Patch every exact W=0/GQR0/non-indexed PSQ pair site in one image."""
    chunks = Path(generated) / "chunks"
    if not chunks.is_dir():
        raise RuntimeError(
            f"GMFE69 global PSQ postgen: missing chunks directory: {chunks}"
        )

    total_load = 0
    total_store = 0
    include_anchor = '#include "../generated.h"\n'

    for path in sorted(chunks.glob("*.c")):
        text = path.read_text()
        original = text

        load_matches = list(PSQ_PAIR_LOAD_RE.finditer(text))
        store_matches = list(PSQ_PAIR_STORE_RE.finditer(text))

        if not load_matches and not store_matches:
            continue

        if PSQ_PAIR_PROTO_MARK not in text:
            if include_anchor not in text:
                raise RuntimeError(
                    f"GMFE69 global PSQ postgen: "
                    f"{path.name}: generated include anchor not found"
                )
            text = text.replace(
                include_anchor,
                include_anchor + "\n" + PSQ_PAIR_PROTO,
                1,
            )

        def repl_load(match):
            return (
                f"ppc_psq_load0_pair_gmfe69_fast("
                f"ctx, {match.group(1)}u, ea, {match.group(2)}) "
                f"/* {PSQ_PAIR_SITE_MARK} {PSQ_PAIR_GLOBAL_MARK} */"
            )

        def repl_store(match):
            return (
                f"ppc_psq_store0_pair_gmfe69_fast("
                f"ctx, {match.group(1)}u, ea, {match.group(2)}) "
                f"/* {PSQ_PAIR_SITE_MARK} {PSQ_PAIR_GLOBAL_MARK} */"
            )

        text, nload = PSQ_PAIR_LOAD_RE.subn(repl_load, text)
        text, nstore = PSQ_PAIR_STORE_RE.subn(repl_store, text)

        if nload != len(load_matches) or nstore != len(store_matches):
            raise RuntimeError(
                f"GMFE69 global PSQ postgen: {path.name}: "
                f"replacement mismatch "
                f"{nload}/{len(load_matches)} loads, "
                f"{nstore}/{len(store_matches)} stores"
            )

        if text != original:
            path.write_text(text)

        total_load += nload
        total_store += nstore

    # Exact candidate form must be fully eliminated for this image.
    remaining_load = 0
    remaining_store = 0
    for path in sorted(chunks.glob("*.c")):
        text = path.read_text()
        remaining_load += len(PSQ_PAIR_LOAD_RE.findall(text))
        remaining_store += len(PSQ_PAIR_STORE_RE.findall(text))

    if remaining_load or remaining_store:
        raise RuntimeError(
            "GMFE69 global PSQ postgen: exact generic pair sites remain: "
            f"{remaining_load} loads + {remaining_store} stores"
        )

    if total_load or total_store:
        print(
            "  GMFE69 global PSQ pair fastpath: "
            f"{total_load} loads + {total_store} stores"
        )

    return total_load, total_store



# MOH_GMFE69_GLOBAL_FP_PERMANENT_POSTGEN
FP_CALL_RE = re.compile(r"\bppc_fp_available\s*\(\s*ctx\s*,")


def _patch_global_fp_available(generated: Path) -> tuple[int, int]:
    """Apply the validated MSR[FP] fast wrapper to every generated FP chunk."""
    chunks = Path(generated) / "chunks"
    if not chunks.is_dir():
        raise RuntimeError(
            f"GMFE69 global FP postgen: missing chunks directory: {chunks}"
        )

    total_sites = 0
    patched_files = 0

    for path in sorted(chunks.glob("*.c")):
        text = path.read_text()
        sites = len(FP_CALL_RE.findall(text))
        if not sites:
            continue

        total_sites += sites

        if FP_MARK not in text:
            if not _patch_hot_fp(path):
                raise RuntimeError(
                    f"GMFE69 global FP postgen: {path.name}: "
                    "failed to install FP wrapper"
                )
            patched_files += 1

    remaining = 0
    covered_files = 0

    for path in sorted(chunks.glob("*.c")):
        text = path.read_text()
        sites = len(FP_CALL_RE.findall(text))
        if not sites:
            continue
        if FP_MARK in text:
            covered_files += 1
        else:
            remaining += sites

    if remaining:
        raise RuntimeError(
            f"GMFE69 global FP postgen: {remaining} generated "
            "ppc_fp_available call sites remain unwrapped"
        )

    if total_sites:
        print(
            "  GMFE69 global FP availability fastpath: "
            f"{total_sites} call sites across {covered_files} chunks "
            f"({patched_files} newly patched)"
        )

    return total_sites, patched_files



# MOH_GMFE69_SPLIT_CROSSCHUNK_RETURNS
RETURN_DISPATCH_GOTO_RE = re.compile(
    r"\bgoto\s+return_dispatch_([0-9A-Fa-f]{8})\s*;"
)
RETURN_DISPATCH_LABEL_RE = re.compile(
    r"(?m)^\s*return_dispatch_([0-9A-Fa-f]{8})\s*:"
)


def _patch_split_crosschunk_returns(generated: Path) -> tuple[int, int]:
    """Route only impossible cross-C-file local returns back to the dispatcher.

    DolRecomp's C local-return optimization emits:
        ctx->pc = target;
        goto return_dispatch_XXXXXXXX;

    With smaller C chunks, a PPC function/call-return region can cross a C-file
    boundary.  If the target local-dispatch label is not present in this same
    generated C file, a C goto is impossible.  `ctx->pc` is already exact, so
    returning from the chunk preserves semantics and lets the chassis/native
    dispatcher continue at that PC.
    """
    chunks = Path(generated) / "chunks"
    if not chunks.is_dir():
        raise RuntimeError(
            f"GMFE69 split-return postgen: missing chunks directory: {chunks}"
        )

    patched_gotos = 0
    patched_files = 0

    for path in sorted(chunks.glob("*.c")):
        text = path.read_text()
        gotos = list(RETURN_DISPATCH_GOTO_RE.finditer(text))
        if not gotos:
            continue

        labels = {
            m.group(1).upper()
            for m in RETURN_DISPATCH_LABEL_RE.finditer(text)
        }

        changed = 0

        def repl(match):
            nonlocal changed
            target = match.group(1).upper()
            if target in labels:
                return match.group(0)

            changed += 1
            return (
                "return; "
                f"/* MOH_GMFE69_SPLIT_CROSSCHUNK_RETURN "
                f"return_dispatch_{target} */"
            )

        new_text = RETURN_DISPATCH_GOTO_RE.sub(repl, text)
        if changed:
            path.write_text(new_text)
            patched_files += 1
            patched_gotos += changed

    # Verify that every remaining goto resolves to a label in the same C file.
    unresolved = []
    for path in sorted(chunks.glob("*.c")):
        text = path.read_text(errors="ignore")
        labels = {
            m.group(1).upper()
            for m in RETURN_DISPATCH_LABEL_RE.finditer(text)
        }
        for m in RETURN_DISPATCH_GOTO_RE.finditer(text):
            target = m.group(1).upper()
            if target not in labels:
                unresolved.append((path.name, target))

    if unresolved:
        sample = ", ".join(
            f"{name}->return_dispatch_{target}"
            for name, target in unresolved[:8]
        )
        raise RuntimeError(
            "GMFE69 split-return postgen: unresolved generated gotos remain: "
            + sample
        )

    if patched_gotos:
        print(
            "  GMFE69 split cross-chunk returns: "
            f"{patched_gotos} goto(s) in {patched_files} chunk(s) "
            "routed through dispatcher"
        )

    return patched_gotos, patched_files



# MOH_GMFE69_FCTIWZ_PERMANENT_POSTGEN
FCTIWZ_SITE_MARK = "MOH_GMFE69_FCTIWZ_SITE"
FCTIWZ_PROTO_MARK = "MOH_GMFE69_FCTIWZ_PROTO"
FCTIWZ_CALL_RE = re.compile(
    r"ppc_fctiw\(\s*ctx\s*,\s*(?P<value>[^,\n]+?)\s*,\s*"
    r"true\s*,\s*&result\s*\)"
)
FCTIWZ_PROTO = r"""
/* MOH_GMFE69_FCTIWZ_PROTO */
extern bool ppc_fctiwz_gmfe69_fast(
    CPUState* cpu, f64 value, u64* output);
"""


def _patch_global_fctiwz_generated(generated: Path) -> tuple[int, int]:
    chunks = Path(generated) / "chunks"
    if not chunks.is_dir():
        raise RuntimeError(
            f"GMFE69 fctiwz postgen: missing chunks directory: {chunks}"
        )

    total = 0
    files = 0
    include_anchor = '#include "../generated.h"\n'

    for path in sorted(chunks.glob("*.c")):
        text = path.read_text()
        matches = list(FCTIWZ_CALL_RE.finditer(text))
        if not matches:
            continue

        if FCTIWZ_PROTO_MARK not in text:
            if include_anchor not in text:
                raise RuntimeError(
                    f"{path}: generated include anchor missing for fctiwz"
                )
            text = text.replace(
                include_anchor,
                include_anchor + "\n" + FCTIWZ_PROTO + "\n",
                1,
            )

        def repl(match):
            return (
                "ppc_fctiwz_gmfe69_fast("
                f"ctx, {match.group('value')}, &result) "
                f"/* {FCTIWZ_SITE_MARK} */"
            )

        text, count = FCTIWZ_CALL_RE.subn(repl, text)
        path.write_text(text)
        total += count
        files += 1

    remaining = 0
    for path in sorted(chunks.glob("*.c")):
        remaining += len(FCTIWZ_CALL_RE.findall(path.read_text(errors="ignore")))

    if remaining:
        raise RuntimeError(
            f"GMFE69 fctiwz postgen: {remaining} generic fctiwz sites remain"
        )

    if total:
        print(
            f"  GMFE69 FCTIWZ fastpath: {total} sites across {files} chunks"
        )

    return total, files




# MOH_GMFE69_FMA_DOUBLE_GLOBAL
FMA_DOUBLE_GLOBAL_MARK = "MOH_GMFE69_FMA_DOUBLE_FAST_SITE"


def _patch_global_fma_double_generated(generated: Path) -> tuple[int, int]:
    """Route finite double-precision PPC FMA sites through the exact fast helper."""
    chunks = Path(generated) / "chunks"
    if not chunks.is_dir():
        raise RuntimeError(f"GMFE69 double-FMA postgen: missing chunks directory: {chunks}")

    pattern = re.compile(
        r"ppc_fma\(\s*ctx\s*,\s*"
        r"(ctx->fpr\[\d+\])\s*,\s*"
        r"(ctx->fpr\[\d+\])\s*,\s*"
        r"(ctx->fpr\[\d+\])\s*,\s*"
        r"false\s*,\s*(true|false)\s*,\s*(true|false)\s*,\s*&result\s*\)"
    )

    total = 0
    files = 0
    for path in sorted(chunks.glob("*.c")):
        text = path.read_text()
        if FMA_DOUBLE_GLOBAL_MARK in text:
            continue

        def repl(match: re.Match[str]) -> str:
            nonlocal total
            total += 1
            return (
                "ppc_fma_double_gmfe69_fast(ctx, "
                f"{match.group(1)}, {match.group(2)}, {match.group(3)}, "
                f"{match.group(4)}, {match.group(5)}, &result) "
                f"/* {FMA_DOUBLE_GLOBAL_MARK} */"
            )

        patched, count = pattern.subn(repl, text)
        if count:
            path.write_text(patched)
            files += 1

    print(f"  GMFE69 global double-FMA fastpath: {total} sites across {files} chunks")
    return total, files


# MOH_GMFE69_CSCREEN_WAIT_IDLE_BACKEDGE
CSCREEN_WAIT_IDLE_MARK = "MOH_GMFE69_CSCREEN_WAIT_IDLE_BACKEDGE"
CSCREEN_WAIT_PC = 0x8001B92C


def _patch_cscreen_wait_idle_backedge(generated: Path) -> int:
    """Make CScreen::Wait return to the chassis after one guest loop iteration.

    The runtime already recognizes 0x8001B92C as a GMFE69 idle PC and calls
    CoreTiming::Idle() when the generated code returns there.  DolRecomp's C
    backend normally keeps local backedges inside the generated function until
    256 guest cycles have accumulated, which defeats most of that idle skip.
    Tightening only this validated busy-wait backedge to its three-cycle block
    cost preserves the condition re-read while yielding to CoreTiming after
    each unsuccessful poll.
    """
    chunks = Path(generated) / "chunks"
    path = _find_chunk_for_pc(chunks, CSCREEN_WAIT_PC)
    if not path:
        return 0

    text = path.read_text()
    start, end = _block_bounds(text, CSCREEN_WAIT_PC)
    block = text[start:end]
    if CSCREEN_WAIT_IDLE_MARK in block:
        return 1

    pattern = re.compile(
        r"(?P<indent>\s*)if \(ctx->downcount <= -\(s64\)"
        r"DOLRECOMP_C_LOOP_CYCLE_BUDGET\) \{\n"
        r"(?P=indent)    ctx->pc = 0x8001B92C(?:u|U)?;\n"
        r"(?P=indent)    return;\n"
        r"(?P=indent)\}"
    )
    matches = list(pattern.finditer(block))
    if len(matches) != 1:
        raise RuntimeError(
            "GMFE69 CScreen::Wait idle postgen: expected one 0x8001B92C "
            f"backedge guard, found {len(matches)} in {path.name}"
        )

    def repl(match: re.Match[str]) -> str:
        indent = match.group("indent")
        return (
            f"{indent}/* {CSCREEN_WAIT_IDLE_MARK}: one poll, then CoreTiming::Idle. */\n"
            f"{indent}if (ctx->downcount <= -(s64)3) {{\n"
            f"{indent}    ctx->pc = 0x8001B92Cu;\n"
            f"{indent}    return;\n"
            f"{indent}}}"
        )

    block = pattern.sub(repl, block, count=1)
    path.write_text(text[:start] + block + text[end:])
    print(f"  GMFE69 CScreen::Wait idle backedge: {path.name} -> 3 cycles")
    return 1

def apply_gmfe69_generated_postgen(generated: Path) -> None:
    generated = Path(generated)
    chunks = generated / "chunks"
    if not chunks.is_dir():
        raise RuntimeError(f"GMFE69 postgen: missing chunks directory: {chunks}")

    _patch_split_crosschunk_returns(generated)

    # perf: CScreen::Wait is the dominant GMFE69 CPU busy-wait.  Return after
    # one three-cycle poll so the runtime's idle-PC hook can advance CoreTiming.
    _patch_cscreen_wait_idle_backedge(generated)

    # Validated globally: inline the overwhelmingly-common MSR[FP] enabled case
    # in every generated chunk, preserving ppc_fp_available() as the exact slow path.
    _patch_global_fp_available(generated)

    # perf: generic double PPC FMA still accounts for a measurable share of
    # GMFE69 CPU time. Finite results use the exact hardware-FMA common path;
    # NaN/Inf/exceptional cases fall back to ppc_fma().
    _patch_global_fma_double_generated(generated)

    _patch_global_psq_pair_generated(generated)


    # Particle-specific PCs survive DolRecomp chunk-size changes.
    _patch_global_fctiwz_generated(generated)

    particle = _find_chunk_for_pc(chunks, 0x8007E198)
    if not particle:
        return

    for path in sorted(chunks.glob("*.c")):
        t = path.read_text(errors="ignore")
        if "MOH_PARTICLE_DEAD_STACK_STORE" in t:
            raise RuntimeError(
                "GMFE69 postgen: obsolete dead-stack-store experiment is "
                f"present in {path.name}; regenerate clean output first"
            )

    text = particle.read_text()
    text = _patch_particle_lfd(text)
    text = _patch_particle_stack(text)
    text = _patch_particle_rng(text)
    text = _patch_particle_fmadds(text)
    particle.write_text(text)

    stack_lfs_total = 0
    stack_lfs_files = 0
    for path in sorted(chunks.glob("*.c")):
        t = path.read_text()
        patched, count = _patch_particle_stack_lfs(
            t, 0x8007AE80, 0x8007EE80
        )
        if count:
            stack_lfs_total += count
            stack_lfs_files += 1
            if patched != t:
                path.write_text(patched)

    if stack_lfs_total != 144:
        raise RuntimeError(
            "GMFE69 postgen: expected 144 particle-region stack LFS sites "
            f"across split chunks, found {stack_lfs_total}"
        )

    generated_texts = [
        path.read_text(errors="ignore")
        for path in sorted(chunks.glob("*.c"))
    ]
    final = "\n".join(generated_texts)

    checks = {
        LFD_MARK: 11,
        STACK_MARK: 7,
        RNG_MARK: 11,
        FMADDS_MARK: 39,
        FMADDS_PROTO_MARK: 1,
        STACK_LFS_MARK: 144,
        STACK_HELPER_MARK: 1,
        MEM1_MARK: 1,
        RESERVE_MARK: 1,
        CSCREEN_WAIT_IDLE_MARK: 1,
    }
    for marker, expected in checks.items():
        count = final.count(marker)
        if count != expected:
            raise RuntimeError(
                f"GMFE69 postgen: marker {marker} count={count}, "
                f"expected={expected}"
            )

    helper_files = 0
    for text_part in generated_texts:
        if STACK_LFS_MARK in text_part:
            if STACK_LFS_HELPER_MARK not in text_part:
                raise RuntimeError(
                    "GMFE69 postgen: stack-LFS site exists without local helper"
                )
            helper_files += 1

    if helper_files != stack_lfs_files:
        raise RuntimeError(
            "GMFE69 postgen: stack-LFS helper/file accounting mismatch: "
            f"helpers={helper_files}, patched-files={stack_lfs_files}"
        )

    print(
        "  GMFE69 particle split-aware postgen: "
        f"hot={particle.name}, stack-lfs={stack_lfs_total} "
        f"across {stack_lfs_files} chunk(s)"
    )




# MOH_GMFE69_BURST_FINAL_FASTPATHS
def _patch_final_burst_fastpaths(text: str) -> str:
    if "MOH_GMFE69_BURST_ADJACENT_CHUNK_FASTPATH" in text:
        return text

    old = """    int cached_chunk = -1;
    u32 cached_chunk_start = 0u;
    u32 cached_chunk_end = 0u;
    ctx->pc = address;
    while (blocks < 64u && total_cycles < cycle_budget) {
        const u32 pc = ctx->pc;
        int chunk = cached_chunk;
        if (chunk < 0 || pc < cached_chunk_start || pc >= cached_chunk_end) {
            chunk = multi_chunk_index(pc);
            if (chunk < 0) break;
            cached_chunk = chunk;
            cached_chunk_start = s_chunk_ranges[(u32)chunk].start;
            cached_chunk_end = s_chunk_ranges[(u32)chunk].end;
        }
        if ((u32)chunk >= chain_state_count || chain_state[(u32)chunk] == 0u) break;
        const u32 begin = s_variant_offsets[(u32)chunk];
        const u32 end = s_variant_offsets[(u32)chunk + 1u];
        /* Never burst through an address range shared by executable images. */
        if (end - begin != 1u) break;
        const u32 image = s_active_image[(u32)chunk];
        if (image == MULTI_INVALID_IMAGE) break;
        ctx->downcount = 0;
"""

    new = """    int cached_chunk = -1;
    u32 cached_chunk_start = 0u;
    u32 cached_chunk_end = 0u;
    u32 cached_image = MULTI_INVALID_IMAGE;
    ctx->pc = address;
    while (blocks < 64u && total_cycles < cycle_budget) {
        const u32 pc = ctx->pc;
        int chunk = cached_chunk;
        if (chunk < 0 || pc < cached_chunk_start || pc >= cached_chunk_end) {
            int resolved_chunk = -1;

            /* MOH_GMFE69_BURST_ADJACENT_CHUNK_FASTPATH */
            if (chunk >= 0) {
                const u32 next = (u32)chunk + 1u;
                if (next < chain_state_count &&
                    pc >= s_chunk_ranges[next].start &&
                    pc < s_chunk_ranges[next].end) {
                    resolved_chunk = (int)next;
                } else if (chunk > 0) {
                    const u32 prev = (u32)chunk - 1u;
                    if (pc >= s_chunk_ranges[prev].start &&
                        pc < s_chunk_ranges[prev].end) {
                        resolved_chunk = (int)prev;
                    }
                }
            }

            if (resolved_chunk < 0)
                resolved_chunk = multi_chunk_index(pc);

            chunk = resolved_chunk;
            if (chunk < 0) break;

            cached_chunk = chunk;
            cached_chunk_start = s_chunk_ranges[(u32)chunk].start;
            cached_chunk_end = s_chunk_ranges[(u32)chunk].end;

            /* MOH_GMFE69_BURST_GUARD_HOIST */
            if ((u32)chunk >= chain_state_count ||
                chain_state[(u32)chunk] == 0u)
                break;

            const u32 begin = s_variant_offsets[(u32)chunk];
            const u32 end = s_variant_offsets[(u32)chunk + 1u];
            if (end - begin != 1u)
                break;

            cached_image = s_active_image[(u32)chunk];
            if (cached_image == MULTI_INVALID_IMAGE)
                break;
        }

        const u32 image = cached_image;
        ctx->downcount = 0;
"""

    count = text.count(old)
    if count != 1:
        if "MOH_GMFE69_BURST_GUARD_HOIST" in text:
            if "MOH_GMFE69_BURST_ADJACENT_CHUNK_FASTPATH" not in text:
                raise RuntimeError(
                    "GMFE69 burst postgen: guard-hoist exists but adjacent "
                    "fastpath is absent"
                )
            return text
        raise RuntimeError(
            f"GMFE69 burst postgen: expected one base burst body, found {count}"
        )

    return text.replace(old, new, 1)


def _image_dispatch_cases(text: str) -> list[tuple[int, str]]:
    cases = [
        (int(index), name)
        for index, name in re.findall(
            r"case\s+(\d+)u:\s+return\s+(mg_image_\d+_dispatch)\(ctx,\s*address\);",
            text,
        )
    ]
    if not cases:
        raise RuntimeError("GMFE69 export postgen: image dispatch cases not found")
    return cases


def _final_burst(cases: list[tuple[int, str]]) -> str:
    case_lines = "".join(
        f"            case {index}u: dispatched = {name}(ctx, pc); break;\n"
        for index, name in cases
    )
    return (
        "static u32 chassis_dispatch_burst(\n"
        "    CPUState* ctx,\n"
        "    u32 address,\n"
        "    const u8* chain_state,\n"
        "    u32 chain_state_count,\n"
        "    u64 cycle_budget,\n"
        "    u64 timebase_origin,\n"
        "    u64 timebase_cycles_before,\n"
        "    u32 timebase_ratio)\n"
        "{\n"
        "    /* MOH_GMFE69_BURST_POSTGEN: validated multi-image native burst. */\n"
        "    multi_init_once();\n"
        "    if (!chain_state || chain_state_count == 0u || cycle_budget == 0u) return 0u;\n"
        "    u32 blocks = 0u;\n"
        "    u64 total_cycles = 0u;\n"
        "    int cached_chunk = -1;\n"
        "    u32 cached_chunk_start = 0u;\n"
        "    u32 cached_chunk_end = 0u;\n"
        "    ctx->pc = address;\n"
        "    while (blocks < 64u && total_cycles < cycle_budget) {\n"
        "        const u32 pc = ctx->pc;\n"
        "        int chunk = cached_chunk;\n"
        "        if (chunk < 0 || pc < cached_chunk_start || pc >= cached_chunk_end) {\n"
        "            chunk = multi_chunk_index(pc);\n"
        "            if (chunk < 0) break;\n"
        "            cached_chunk = chunk;\n"
        "            cached_chunk_start = s_chunk_ranges[(u32)chunk].start;\n"
        "            cached_chunk_end = s_chunk_ranges[(u32)chunk].end;\n"
        "        }\n"
        "        if ((u32)chunk >= chain_state_count || chain_state[(u32)chunk] == 0u) break;\n"
        "        const u32 begin = s_variant_offsets[(u32)chunk];\n"
        "        const u32 end = s_variant_offsets[(u32)chunk + 1u];\n"
        "        /* Never burst through an address range shared by executable images. */\n"
        "        if (end - begin != 1u) break;\n"
        "        const u32 image = s_active_image[(u32)chunk];\n"
        "        if (image == MULTI_INVALID_IMAGE) break;\n"
        "        ctx->downcount = 0;\n"
        "        int dispatched = 0;\n"
        "        switch (image) {\n"
        + case_lines +
        "            default: break;\n"
        "        }\n"
        "        if (!dispatched) break;\n"
        "        const s64 raw_charge = -ctx->downcount;\n"
        "        const u64 charge = raw_charge > 0 ? (u64)raw_charge : 1u;\n"
        "        total_cycles += charge;\n"
        "        ++blocks;\n"
        "        if (timebase_ratio != 0u) {\n"
        "            const u64 tb_cycles = timebase_cycles_before + total_cycles;\n"
        "            u64 tb_delta;\n"
        "#if defined(__GNUC__) || defined(__clang__)\n"
        "            if (__builtin_expect(timebase_ratio == 12u, 1))\n"
        "#else\n"
        "            if (timebase_ratio == 12u)\n"
        "#endif\n"
        "                tb_delta = tb_cycles / 12u;\n"
        "            else\n"
        "                tb_delta = chassis_div_u64_u32(tb_cycles, timebase_ratio);\n"
        "            ctx->timebase = timebase_origin + tb_delta;\n"
        "        }\n"
        "        ctx->downcount = 0;\n"
        "        if (ctx->exception) break;\n"
        "    }\n"
        "    ctx->downcount = -(s64)total_cycles;\n"
        "    return blocks;\n"
        "}\n\n"
    )


DIV_HELPER = r'''#if defined(__GNUC__) || defined(__clang__)
__attribute__((noinline))
#endif
static u64 chassis_div_u64_u32(u64 value, u32 divisor)
{
    return value / divisor;
}

'''


def apply_gmfe69_export_postgen(path: Path) -> None:
    path = Path(path)
    text = path.read_text()
    cases = _image_dispatch_cases(text)
    state_anchor = "static void chassis_on_state_loaded(CPUState* ctx)\n"
    if state_anchor not in text:
        raise RuntimeError("GMFE69 export postgen: chassis_on_state_loaded anchor not found")

    start = text.find("static u32 chassis_dispatch_burst(")
    if start < 0:
        start = text.find("static int chassis_dispatch_burst(")
    if start >= 0:
        end = text.find(state_anchor, start)
        if end < 0:
            raise RuntimeError("GMFE69 export postgen: malformed existing burst function")
        # Replace only the burst function.
        #
        # Do NOT move `start` backwards to the /12 divider helper: the generated
        # export places `chassis_dispatch()` between that helper and the burst.
        # Moving `start` to the helper would therefore delete the normal
        # dispatcher while s_desc still references it.
        text = text[:start] + _final_burst(cases) + text[end:]
    else:
        pos = text.find(state_anchor)
        text = text[:pos] + _final_burst(cases) + text[pos:]

    burst_pos = text.find("static u32 chassis_dispatch_burst(")
    if "static u64 chassis_div_u64_u32(" not in text:
        text = text[:burst_pos] + DIV_HELPER + text[burst_pos:]

    descriptor_pattern = re.compile(
        r"(?m)^(\s*)(?:0|chassis_dispatch_burst)\s*,[^\n]*\n"
        r"(\s*multi_select_chunk_variant\s*,)"
    )
    matches = list(descriptor_pattern.finditer(text))
    if not matches:
        raise RuntimeError("GMFE69 export postgen: burst descriptor field not found")
    match = matches[-1]
    indent = match.group(1)
    text = (
        text[:match.start()]
        + f"{indent}chassis_dispatch_burst, /* unique-image chunks only */\n"
        + match.group(2)
        + text[match.end():]
    )
    text = _patch_final_burst_fastpaths(text)
    path.write_text(text)

    final = path.read_text()
    required = (
        "MOH_GMFE69_BURST_POSTGEN",
        "cached_chunk_start",
        "int dispatched = 0;",
        "chassis_div_u64_u32",
        "timebase_ratio == 12u",
        "chassis_dispatch_burst, /* unique-image chunks only */",
    )
    for marker in required:
        if marker not in final:
            raise RuntimeError(f"GMFE69 export postgen: missing verification marker: {marker}")
    burst_start = final.find("static u32 chassis_dispatch_burst(")
    burst_end = final.find(state_anchor, burst_start)
    burst = final[burst_start:burst_end]
    if "chassis_dispatch(ctx, pc)" in burst:
        raise RuntimeError("GMFE69 export postgen: second binary-search dispatcher survived in burst")


__all__ = (
    "apply_gmfe69_generated_postgen",
    "apply_gmfe69_export_postgen",
)
